---
name: Go build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -cover ./...

      - name: Test flakiness
        # Run the unit tests with a high count to check for flakiness
        # Yes, we really can run the tests 100000 times in just a few seconds
        run: go test -count 100000 -failfast -skip '^Example' ./...
